// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jdholdren/seymour/internal/seymour (interfaces: FeedService,TimelineService,UserService)
//
// Generated by this command:
//
//	mockgen -destination=../mock/seymour.go -package=mock . FeedService,TimelineService,UserService
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	seymour "github.com/jdholdren/seymour/internal/seymour"
	gomock "go.uber.org/mock/gomock"
)

// MockFeedService is a mock of FeedService interface.
type MockFeedService struct {
	ctrl     *gomock.Controller
	recorder *MockFeedServiceMockRecorder
	isgomock struct{}
}

// MockFeedServiceMockRecorder is the mock recorder for MockFeedService.
type MockFeedServiceMockRecorder struct {
	mock *MockFeedService
}

// NewMockFeedService creates a new mock instance.
func NewMockFeedService(ctrl *gomock.Controller) *MockFeedService {
	mock := &MockFeedService{ctrl: ctrl}
	mock.recorder = &MockFeedServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedService) EXPECT() *MockFeedServiceMockRecorder {
	return m.recorder
}

// CountAllFeeds mocks base method.
func (m *MockFeedService) CountAllFeeds(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAllFeeds", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAllFeeds indicates an expected call of CountAllFeeds.
func (mr *MockFeedServiceMockRecorder) CountAllFeeds(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAllFeeds", reflect.TypeOf((*MockFeedService)(nil).CountAllFeeds), ctx)
}

// DeleteFeed mocks base method.
func (m *MockFeedService) DeleteFeed(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFeed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFeed indicates an expected call of DeleteFeed.
func (mr *MockFeedServiceMockRecorder) DeleteFeed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFeed", reflect.TypeOf((*MockFeedService)(nil).DeleteFeed), ctx, id)
}

// Entries mocks base method.
func (m *MockFeedService) Entries(ctx context.Context, ids []string) ([]seymour.FeedEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Entries", ctx, ids)
	ret0, _ := ret[0].([]seymour.FeedEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Entries indicates an expected call of Entries.
func (mr *MockFeedServiceMockRecorder) Entries(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Entries", reflect.TypeOf((*MockFeedService)(nil).Entries), ctx, ids)
}

// Entry mocks base method.
func (m *MockFeedService) Entry(ctx context.Context, id string) (seymour.FeedEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Entry", ctx, id)
	ret0, _ := ret[0].(seymour.FeedEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Entry indicates an expected call of Entry.
func (mr *MockFeedServiceMockRecorder) Entry(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Entry", reflect.TypeOf((*MockFeedService)(nil).Entry), ctx, id)
}

// Feed mocks base method.
func (m *MockFeedService) Feed(ctx context.Context, id string) (seymour.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Feed", ctx, id)
	ret0, _ := ret[0].(seymour.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Feed indicates an expected call of Feed.
func (mr *MockFeedServiceMockRecorder) Feed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Feed", reflect.TypeOf((*MockFeedService)(nil).Feed), ctx, id)
}

// FeedByURL mocks base method.
func (m *MockFeedService) FeedByURL(ctx context.Context, url string) (seymour.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FeedByURL", ctx, url)
	ret0, _ := ret[0].(seymour.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FeedByURL indicates an expected call of FeedByURL.
func (mr *MockFeedServiceMockRecorder) FeedByURL(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FeedByURL", reflect.TypeOf((*MockFeedService)(nil).FeedByURL), ctx, url)
}

// FeedIDs mocks base method.
func (m *MockFeedService) FeedIDs(ctx context.Context, offset, pageSize int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FeedIDs", ctx, offset, pageSize)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FeedIDs indicates an expected call of FeedIDs.
func (mr *MockFeedServiceMockRecorder) FeedIDs(ctx, offset, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FeedIDs", reflect.TypeOf((*MockFeedService)(nil).FeedIDs), ctx, offset, pageSize)
}

// Feeds mocks base method.
func (m *MockFeedService) Feeds(ctx context.Context, ids []string) ([]seymour.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Feeds", ctx, ids)
	ret0, _ := ret[0].([]seymour.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Feeds indicates an expected call of Feeds.
func (mr *MockFeedServiceMockRecorder) Feeds(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Feeds", reflect.TypeOf((*MockFeedService)(nil).Feeds), ctx, ids)
}

// InsertEntries mocks base method.
func (m *MockFeedService) InsertEntries(ctx context.Context, entries []seymour.FeedEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEntries", ctx, entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertEntries indicates an expected call of InsertEntries.
func (mr *MockFeedServiceMockRecorder) InsertEntries(ctx, entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEntries", reflect.TypeOf((*MockFeedService)(nil).InsertEntries), ctx, entries)
}

// InsertFeed mocks base method.
func (m *MockFeedService) InsertFeed(ctx context.Context, url string) (seymour.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertFeed", ctx, url)
	ret0, _ := ret[0].(seymour.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertFeed indicates an expected call of InsertFeed.
func (mr *MockFeedServiceMockRecorder) InsertFeed(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertFeed", reflect.TypeOf((*MockFeedService)(nil).InsertFeed), ctx, url)
}

// UpdateFeed mocks base method.
func (m *MockFeedService) UpdateFeed(ctx context.Context, id string, args seymour.UpdateFeedArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFeed", ctx, id, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFeed indicates an expected call of UpdateFeed.
func (mr *MockFeedServiceMockRecorder) UpdateFeed(ctx, id, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFeed", reflect.TypeOf((*MockFeedService)(nil).UpdateFeed), ctx, id, args)
}

// MockTimelineService is a mock of TimelineService interface.
type MockTimelineService struct {
	ctrl     *gomock.Controller
	recorder *MockTimelineServiceMockRecorder
	isgomock struct{}
}

// MockTimelineServiceMockRecorder is the mock recorder for MockTimelineService.
type MockTimelineServiceMockRecorder struct {
	mock *MockTimelineService
}

// NewMockTimelineService creates a new mock instance.
func NewMockTimelineService(ctrl *gomock.Controller) *MockTimelineService {
	mock := &MockTimelineService{ctrl: ctrl}
	mock.recorder = &MockTimelineServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimelineService) EXPECT() *MockTimelineServiceMockRecorder {
	return m.recorder
}

// AllSubscriptions mocks base method.
func (m *MockTimelineService) AllSubscriptions(ctx context.Context, userID string) ([]seymour.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllSubscriptions", ctx, userID)
	ret0, _ := ret[0].([]seymour.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllSubscriptions indicates an expected call of AllSubscriptions.
func (mr *MockTimelineServiceMockRecorder) AllSubscriptions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllSubscriptions", reflect.TypeOf((*MockTimelineService)(nil).AllSubscriptions), ctx, userID)
}

// CountTimelineEntries mocks base method.
func (m *MockTimelineService) CountTimelineEntries(ctx context.Context, args seymour.TimelineEntriesArgs) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTimelineEntries", ctx, args)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTimelineEntries indicates an expected call of CountTimelineEntries.
func (mr *MockTimelineServiceMockRecorder) CountTimelineEntries(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTimelineEntries", reflect.TypeOf((*MockTimelineService)(nil).CountTimelineEntries), ctx, args)
}

// CreateSubscription mocks base method.
func (m *MockTimelineService) CreateSubscription(ctx context.Context, userID, feedID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscription", ctx, userID, feedID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubscription indicates an expected call of CreateSubscription.
func (mr *MockTimelineServiceMockRecorder) CreateSubscription(ctx, userID, feedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscription", reflect.TypeOf((*MockTimelineService)(nil).CreateSubscription), ctx, userID, feedID)
}

// DeleteSubscription mocks base method.
func (m *MockTimelineService) DeleteSubscription(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubscription", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubscription indicates an expected call of DeleteSubscription.
func (mr *MockTimelineServiceMockRecorder) DeleteSubscription(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubscription", reflect.TypeOf((*MockTimelineService)(nil).DeleteSubscription), ctx, id)
}

// EntriesNeedingJudgement mocks base method.
func (m *MockTimelineService) EntriesNeedingJudgement(ctx context.Context, limit uint) ([]seymour.TimelineEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EntriesNeedingJudgement", ctx, limit)
	ret0, _ := ret[0].([]seymour.TimelineEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EntriesNeedingJudgement indicates an expected call of EntriesNeedingJudgement.
func (mr *MockTimelineServiceMockRecorder) EntriesNeedingJudgement(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EntriesNeedingJudgement", reflect.TypeOf((*MockTimelineService)(nil).EntriesNeedingJudgement), ctx, limit)
}

// InsertEntry mocks base method.
func (m *MockTimelineService) InsertEntry(ctx context.Context, entry seymour.TimelineEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEntry", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertEntry indicates an expected call of InsertEntry.
func (mr *MockTimelineServiceMockRecorder) InsertEntry(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEntry", reflect.TypeOf((*MockTimelineService)(nil).InsertEntry), ctx, entry)
}

// MissingEntries mocks base method.
func (m *MockTimelineService) MissingEntries(ctx context.Context) ([]seymour.MissingEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MissingEntries", ctx)
	ret0, _ := ret[0].([]seymour.MissingEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MissingEntries indicates an expected call of MissingEntries.
func (mr *MockTimelineServiceMockRecorder) MissingEntries(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MissingEntries", reflect.TypeOf((*MockTimelineService)(nil).MissingEntries), ctx)
}

// Subscription mocks base method.
func (m *MockTimelineService) Subscription(ctx context.Context, id string) (seymour.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscription", ctx, id)
	ret0, _ := ret[0].(seymour.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscription indicates an expected call of Subscription.
func (mr *MockTimelineServiceMockRecorder) Subscription(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscription", reflect.TypeOf((*MockTimelineService)(nil).Subscription), ctx, id)
}

// TimelineEntries mocks base method.
func (m *MockTimelineService) TimelineEntries(ctx context.Context, args seymour.TimelineEntriesArgs) ([]seymour.TimelineEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TimelineEntries", ctx, args)
	ret0, _ := ret[0].([]seymour.TimelineEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TimelineEntries indicates an expected call of TimelineEntries.
func (mr *MockTimelineServiceMockRecorder) TimelineEntries(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TimelineEntries", reflect.TypeOf((*MockTimelineService)(nil).TimelineEntries), ctx, args)
}

// UpdateTimelineEntry mocks base method.
func (m *MockTimelineService) UpdateTimelineEntry(ctx context.Context, id string, status seymour.TimelineEntryStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTimelineEntry", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTimelineEntry indicates an expected call of UpdateTimelineEntry.
func (mr *MockTimelineServiceMockRecorder) UpdateTimelineEntry(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTimelineEntry", reflect.TypeOf((*MockTimelineService)(nil).UpdateTimelineEntry), ctx, id, status)
}

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// EnsureUser mocks base method.
func (m *MockUserService) EnsureUser(ctx context.Context, idp seymour.Idp, id string) (seymour.User, seymour.UserLogin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureUser", ctx, idp, id)
	ret0, _ := ret[0].(seymour.User)
	ret1, _ := ret[1].(seymour.UserLogin)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// EnsureUser indicates an expected call of EnsureUser.
func (mr *MockUserServiceMockRecorder) EnsureUser(ctx, idp, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureUser", reflect.TypeOf((*MockUserService)(nil).EnsureUser), ctx, idp, id)
}

// UpdateUser mocks base method.
func (m *MockUserService) UpdateUser(ctx context.Context, id string, args seymour.UpdateUserArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, id, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserServiceMockRecorder) UpdateUser(ctx, id, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserService)(nil).UpdateUser), ctx, id, args)
}

// User mocks base method.
func (m *MockUserService) User(ctx context.Context, id string) (seymour.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User", ctx, id)
	ret0, _ := ret[0].(seymour.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// User indicates an expected call of User.
func (mr *MockUserServiceMockRecorder) User(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockUserService)(nil).User), ctx, id)
}
